# Loading Numpy


In [1]:
import numpy as np

## 1. Create numpy array



In [2]:
# array from python list

list1 = [2,4,6,8,10]

arr1 = np.array(list1)



In [3]:
arr1


array([ 2,  4,  6,  8, 10])

In [4]:
list1

[2, 4, 6, 8, 10]

In [5]:
type(list1)


list

In [6]:
type(arr1)

numpy.ndarray

##### why we need array as we have list


In [7]:
# Verterize operations are not possible on list but they are possible on array

# lets see using array+1 and list+1 as we can see array add 1 to each element but list give error

In [8]:
arr1+2

array([ 4,  6,  8, 10, 12])

In [9]:
try:
    list1+1
except Exception as err:
    print("error is there :- " , err)

error is there :-  can only concatenate list (not "int") to list


In [10]:
list2 = [ [9,7,6,4], [2,4,6,7] ]

arr2 = np.array(list2)


In [11]:
arr2

array([[9, 7, 6, 4],
       [2, 4, 6, 7]])

In [12]:
list2

[[9, 7, 6, 4], [2, 4, 6, 7]]

In [13]:
type(arr2)


numpy.ndarray

In [14]:
type(list2)

list

#### Now lets try to convert this integer list to float array using <font color ="red">dtype</font>

In [17]:
list2=[[9, 7, 6, 4], [2, 4, 6, 7]]
list2

[[9, 7, 6, 4], [2, 4, 6, 7]]

In [19]:
arr3 = np.array(list2,dtype="float")
arr3

array([[9., 7., 6., 4.],
       [2., 4., 6., 7.]])

#### Now lets try to convert this float array again to integer array using <font color ="red">astype</font>

In [24]:
arr4 = arr3.astype('int')
print(arr4)
print()
print(arr3)

[[9 7 6 4]
 [2 4 6 7]]

[[9. 7. 6. 4.]
 [2. 4. 6. 7.]]


#### Now lets try to convert this float array to boolean form  # here 0 is false else everything is true

In [28]:
arr5  = np.array(list2,dtype = "bool")
arr5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [29]:
arr6  = arr4.astype("bool")
arr6

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

#### here now lets add to mix these data types mean single array which contains everything like int , float , string


list3 = [[2,3,4.0,"NG"],[3,4,5,"hELLO"]]

arr7 = np.array(list3,dtype="object")

arr7

### convert array to list using <font color = "red">  tolist()</font>

In [32]:
list4 = arr7.tolist()
list4

[[2, 3, 4.0, 'NG'], [3, 4, 5, 'hELLO']]